### DISCUSSION TITLE
Adding a second Xiaomi Philips Ceiling Light to Home Assistant

### DISCUSSION THREAD

**Discussion by DARKFiB3R** [rytilahti/python-miio#1257] [Q&A]
I finally managed to add one light to Home Assistant. Thank you :)

But now I am stuck on adding a second.

I added the first by adding the Xiaomi Philips Lights Integration via HACS, then editing configuration.yaml

```
# Philips connected ceiling
light:
  - platform: xiaomi_miio_philipslight
    name: Back Light
    host: 192.168.50.143
    token: xxxxxxxxxxxxxxxxxxxxxx
    model: philips.light.ceiling
```

Adding a second...

```
# Philips connected ceiling
light:
  - platform: xiaomi_miio_philipslight
    name: Front Light
    host: 192.168.50.17
    token: same token as above
    model: philips.light.ceiling
```
caused a conflict in the editor...

```
duplicated mapping key at line 23, column -168:
    light:
    ^
```
Now niether light works via Home assistant.

If I edit the line "light:" to "light2:" for instance, and then Check Configuration via Server Controls, I get the error...

`Integration error: light2 - Integration 'light2' not found.`

Hope somebody can help. Thanks.

EDIT: Sorry, I realise what I was doing wrong. The config should look like this...

```
# Philips connected ceiling
light:
  - platform: xiaomi_miio_philipslight
    name: Front Light
    host: 192.168.50.17
    token: xxxxxxxxxxxxxxxxxxxxxxxx
    model: philips.light.ceiling
  - platform: xiaomi_miio_philipslight
    name: Back Light
    host: 192.168.50.143
    token: xxxxxxxxxxxxxxxxxxxxxxxx
    model: philips.light.ceiling
```

But the new "Front Light" is still saying unavailable.

So close.... lol

Help!!!

Edit 2: In the Xiaomi App, (Front Light) Additional Settings > Network info, it says Current Mode: Network connection.

For the Back Light, at least for a moment, it said Remote Connection.

What is that all about?
