### ISSUE TITLE
Xiaomi Philips ceiling light automation

### ISSUE THREAD

**Issue by matsube11** [rytilahti/python-miio#116]
I've tried to sort this out on HA forum with no luck:

How do you call the following action in HA automation ?
```miceil --ip 192.168.X.XX --token XXXXXXXXXXXXXXXXXXXXXX set_scene 4```

I've tried that without any success:
```
action:
  - service: light.turn_on   
    entity_id:
    - light.xiaomi_philips_smart_led
    data:
      set_scene: 4
```
Turning it on and off works fine in HA automation but I'd like to be able to call the moonlight function (scene 4)
Thanks
