### ISSUE TITLE
Unsupported model ijai.vacuum.v19

### ISSUE THREAD

**Issue by Revyen** [rytilahti/python-miio#1394]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Xiaomi Robot Vacuum-Mop 2S
  - Link: https://home.miot-spec.com/s/ijai.vacuum.v19

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: ijai.vacuum.v19
  - Hardware version:
  - Firmware version: 4.1.8_0076

**Comment by garritfra** [comment]
I just got a Mop 2s and was bummed to see that it wasn't supported by home assistant.

Please do let me know if anyone is working on supporting this device. If that's not the case, I'm happy to give it a try.

**Comment by Revyen** [comment]
So far I found no working solution or work around. I myself are fairly new to this an la King proper knowledge to implementiert this myself.

If you @garritfra would give it a try I would be gratefull

**Comment by garritfra** [comment]
@Revyen fyi: after digging around a bit I found out that the Mop 2s is actually not based on miio as this tool implies, but it's built on top of the newer miot protocol/API/software product. I got my vacuum into Homeassistant using this extension in the HACS store:

https://github.com/al-one/hass-xiaomi-miot

Triggering individual functions of the robot is extremely finicky, but once you got the hang of how miot works, you can throw together a script that you can reuse. Let me know if you need any help.

**Comment by danichispa** [comment]
> @Revyen fyi: after digging around a bit I found out that the Mop 2s is actually not based on miio as this tool implies, but it's built on top of the newer miot protocol/API/software product. I got my vacuum into Homeassistant using this extension in the HACS store:
> 
> https://github.com/al-one/hass-xiaomi-miot
> 
> Triggering individual functions of the robot is extremely finicky, but once you got the hang of how miot works, you can throw together a script that you can reuse. Let me know if you need any help.

Can u post an example of your scripts? I want to integrate my Mop 2S in HA

**Comment by garritfra** [comment]
Sure. This is a script that cleans a single room:

```
alias: Clean Kitchen
sequence:
  - service: xiaomi_miot.call_action
    data:
      entity_id: vacuum.ijai_v19_9a2c_robot_cleaner. 
      siid: 7   # Service ID for 'sweep'
      aiid: 3   # Action ID for 'set-room-clean'
      params:
        - '10'   # Room ID to clean. I brute forced these IDs to map it to the rooms, but I'm sure there is a working endpoint for this somewhere. 
        - 0      # 0 = 'Global'
        - 1      # 1 = 'start'
mode: single
icon: mdi:sofa-single
```

For the `siid`s and `aiid`s, you can refer to the [spec](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:vacuum:0000A006:ijai-v19:1).

I'm planning on writing this down in more detail on my blog, but you should be able to get started with this.

You might also be interested in [this](https://github.com/denysdovhan/vacuum-card) card. I found that the (probably way superior) [vacuum map card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) didn't work for me out of the box, since extracting the map requires the Vacuum to be on the same LAN as the HA box, which isn't the case for me.
