### ISSUE TITLE
err_state 2100 in STYTJ02YM

### ISSUE THREAD

**Issue by softko** [rytilahti/python-miio#1882]
Hey, just want to inform you that my Mi Robot Vacuum-Mop P (STYTJ02YM) today returned err_state 2100. I haven't found that code anywhere in repository, but it was due to low battery while cleaning. After recharge it cleaned the rest. I have found it under code 2101 in miio/integrations/viomi/vacuum/viomivacuum.py. So it's just FYI if you want to add it.
all attributes at that time (from HA):
```
      fan_speed_list:
        - Silent
        - Standard
        - Medium
        - Turbo
      battery_level: 6
      battery_icon: mdi:battery-10
      fan_speed: Standard
      run_state: 3
      mode: 0
      err_state: 2100
      battary_life: 6
      box_type: 1
      mop_type: 0
      s_time: 23
      s_area: 31.68
      suction_grade: 1
      water_grade: 11
      remember_map: 1
      has_map: 1
      is_mop: 0
      has_newmap: 0
      hw_info: 1.0.1
      sw_info: 3.5.3_0017
      start_time: 0
      order_time: '0'
      v_state: 6
      zone_data: '0'
      repeat_state: 0
      light_state: 1
      is_charge: 1
      is_work: 0
      cleaned_area: 31.68
      cleaning_time: 23
      status: cleaning
      friendly_name: Vacuum V8
      supported_features: 13180
```
