### ISSUE TITLE
Unsupported device chuangmi.plug.hmi206

### ISSUE THREAD

**Issue by Pushkarik** [rytilahti/python-miio#545]
HA says:
> Unsupported device found! Please create an issue at https://github.com/rytilahti/python-miio/issues and provide the following data: chuangmi.plug.hmi206

**Comment by Pushkarik** [comment]
This is smart plug, model zncz05cm, for EU

**Comment by manugc** [comment]
How have you tried that works ?. I look at the database and have no token

**Comment by Pushkarik** [comment]
my working variant with model zncz05cm.
```
switch:
  - platform: xiaomi_miio
    host: 192.168.1.13
    token: !secret plug_16a_token
    **model: chuangmi.plug.hmi205**
```
