### ISSUE TITLE
Mi Smart Baseboard Heater E (zhimi.heater.ma3)

### ISSUE THREAD

**Issue by fineemb** [rytilahti/python-miio#839]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**
[https://cdn.cnbj0.fds.api.mi-img.com/b2c-shopapi-pms/pms_1600695132.81241311.jpg](url)
  - Name(s) of the device: Mi Smart Baseboard Heater E
  - Link:

Use `miiocli device --ip <ip address> --token <token>`.

- Model: zhimi.heater.ma3                                                                                                                                                         
- Hardware version: esp32                                                                                                                                                         
- Firmware version: 2.1.3

**Additional context**
[http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:zhimi-ma3:1](url)

````yaml
# Countdown
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":36000,"siid":3,"piid":1}]'    

# Switch Status
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":True,"siid":2,"piid":1}]'  

# Target Temperature
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":22,"siid":2,"piid":5}]' 

# Mode
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":1,"siid":2,"piid":6}]' 

# Physical Control Locked
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":True,"siid":5,"piid":1}]'

# Alarm
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":True,"siid":6,"piid":1}]'

# Indicator Light
miiocli device --ip <ip address> --token <token> raw_command set_properties '[{"did":"317189583","value":0,"siid":7,"piid":3}]' 

Return:  [{'did': '317189583', 'siid': siid , 'piid': piid, 'code': 0}]

# Get Switch Status
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":1,"siid":2,"did":"317189583"}]' 

# Get fault
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":2,"siid":2,"did":"317189583"}]' 

# Get Target Temperature
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":5,"siid":2,"did":"317189583"}]' 

# Get Mode
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":6,"siid":2,"did":"317189583"}]' 

# Get Environment
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":1,"siid":3,"did":"317189583"}]' 

# Get Temperature
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":7,"siid":4,"did":"317189583"}]' 

# Get Physical Control Locked stauts 
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":1,"siid":5,"did":"317189583"}]' 

# Get Alarm stauts 
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":1,"siid":6,"did":"317189583"}]' 

# Get Alarm stauts 
miiocli device --ip <ip address> --token <token> raw_command get_properties '[{"piid":1,"siid":6,"did":"317189583"}]'

Return: [{'did': '317189583', 'siid': siid, 'piid': piid, 'code': 0, 'value': value}] 
````
